import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from '@react-pdf/renderer'

// ─── Colors ───────────────────────────────────────────────────────────────

const ROYAL_BLUE = '#133378'
const METALLIC_GOLD = '#C8A951'
const SLATE_700 = '#334155'
const SLATE_500 = '#64748B'

// ─── Styles ───────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  page: {
    paddingTop: 72,
    paddingBottom: 80,
    paddingHorizontal: 72,
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: SLATE_700,
    position: 'relative',
  },
  // Header
  headerContainer: {
    marginBottom: 8,
  },
  headerText: {
    fontFamily: 'Times-Roman',
    fontSize: 22,
    color: ROYAL_BLUE,
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  headerTagline: {
    fontFamily: 'Helvetica',
    fontSize: 8,
    color: SLATE_500,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginTop: 2,
  },
  goldRule: {
    height: 2,
    backgroundColor: METALLIC_GOLD,
    marginTop: 12,
    marginBottom: 24,
  },
  // Portrait
  portraitContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  portrait: {
    width: 120,
    height: 120,
    borderRadius: 60,
    objectFit: 'cover',
  },
  // Name
  name: {
    fontFamily: 'Times-Bold',
    fontSize: 28,
    color: '#0F172A',
    textAlign: 'center',
    marginBottom: 6,
    lineHeight: 1.3,
  },
  // Dates
  dates: {
    fontFamily: 'Helvetica',
    fontSize: 12,
    color: SLATE_500,
    textAlign: 'center',
    marginBottom: 20,
    letterSpacing: 1,
  },
  // Memorial border
  memorialFrame: {
    borderWidth: 1,
    borderColor: METALLIC_GOLD,
    borderRadius: 4,
    padding: 24,
    marginBottom: 20,
  },
  // Content body
  paragraph: {
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: SLATE_700,
    lineHeight: 1.8,
    marginBottom: 10,
    textAlign: 'justify' as const,
  },
  // Thin gold rule divider
  thinGoldRule: {
    height: 1,
    backgroundColor: METALLIC_GOLD,
    marginVertical: 16,
    opacity: 0.5,
  },
  // Footer
  footer: {
    position: 'absolute',
    bottom: 36,
    left: 72,
    right: 72,
  },
  footerRule: {
    height: 1,
    backgroundColor: METALLIC_GOLD,
    marginBottom: 8,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerText: {
    fontFamily: 'Helvetica',
    fontSize: 7,
    color: SLATE_500,
  },
  footerBrand: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 7,
    color: ROYAL_BLUE,
  },
  pageNumber: {
    fontFamily: 'Helvetica',
    fontSize: 7,
    color: SLATE_500,
  },
})

// ─── Component Props ──────────────────────────────────────────────────────

export interface ObituaryPDFProps {
  name: string
  content: string
  photoUrl?: string
  birthDate?: string
  deathDate?: string
  date: string
}

// ─── PDF Document Component ───────────────────────────────────────────────

export function ObituaryPDF({
  name,
  content,
  photoUrl,
  birthDate,
  deathDate,
  date,
}: ObituaryPDFProps) {
  // Split plain text into paragraphs
  const paragraphs = content
    .split(/\n\n+/)
    .map((p) => p.trim())
    .filter(Boolean)

  const hasDates = birthDate || deathDate
  const dateString = hasDates
    ? [birthDate, deathDate].filter(Boolean).join(' — ')
    : undefined

  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        {/* Header */}
        <View style={styles.headerContainer} fixed>
          <Text style={styles.headerText}>FinalWishes</Text>
          <Text style={styles.headerTagline}>The Estate Operating System</Text>
        </View>
        <View style={styles.goldRule} fixed />

        {/* Portrait */}
        {photoUrl && (
          <View style={styles.portraitContainer}>
            <Image src={photoUrl} style={styles.portrait} />
          </View>
        )}

        {/* Name */}
        <Text style={styles.name}>{name}</Text>

        {/* Dates */}
        {dateString && <Text style={styles.dates}>{dateString}</Text>}

        {/* Thin divider */}
        <View style={styles.thinGoldRule} />

        {/* Memorial Frame with Content */}
        <View style={styles.memorialFrame}>
          {paragraphs.map((para, i) => (
            <Text key={i} style={styles.paragraph}>
              {para}
            </Text>
          ))}
          {paragraphs.length === 0 && (
            <Text style={styles.paragraph}>No content provided.</Text>
          )}
        </View>

        {/* Footer */}
        <View style={styles.footer} fixed>
          <View style={styles.footerRule} />
          <View style={styles.footerRow}>
            <Text style={styles.footerText}>
              This document was generated by{' '}
              <Text style={styles.footerBrand}>FinalWishes</Text>
              {' '}&mdash; The Estate Operating System &bull; {date}
            </Text>
            <Text
              style={styles.pageNumber}
              render={({ pageNumber, totalPages }) =>
                `Page ${pageNumber} of ${totalPages}`
              }
            />
          </View>
        </View>
      </Page>
    </Document>
  )
}
