/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as EstatesCreateRouteImport } from './routes/estates.create'
import { Route as EstatesEstateIdRouteImport } from './routes/estates.$estateId'
import { Route as DashboardVaultRouteImport } from './routes/dashboard.vault'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardObituaryRouteImport } from './routes/dashboard.obituary'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMemoirsRouteImport } from './routes/dashboard.memoirs'
import { Route as DashboardEstatesRouteImport } from './routes/dashboard.estates'
import { Route as DashboardBeneficiariesRouteImport } from './routes/dashboard.beneficiaries'
import { Route as DashboardAssetsRouteImport } from './routes/dashboard.assets'
import { Route as EstatesEstateIdIndexRouteImport } from './routes/estates.$estateId.index'
import { Route as EstatesEstateIdVaultRouteImport } from './routes/estates.$estateId.vault'
import { Route as EstatesEstateIdSettingsRouteImport } from './routes/estates.$estateId.settings'
import { Route as EstatesEstateIdObituaryRouteImport } from './routes/estates.$estateId.obituary'
import { Route as EstatesEstateIdNotificationsRouteImport } from './routes/estates.$estateId.notifications'
import { Route as EstatesEstateIdMemoirsRouteImport } from './routes/estates.$estateId.memoirs'
import { Route as EstatesEstateIdEstatesRouteImport } from './routes/estates.$estateId.estates'
import { Route as EstatesEstateIdDashboardRouteImport } from './routes/estates.$estateId.dashboard'
import { Route as EstatesEstateIdBeneficiariesRouteImport } from './routes/estates.$estateId.beneficiaries'
import { Route as EstatesEstateIdAttestationRouteImport } from './routes/estates.$estateId.attestation'
import { Route as EstatesEstateIdAssetsRouteImport } from './routes/estates.$estateId.assets'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EstatesCreateRoute = EstatesCreateRouteImport.update({
  id: '/estates/create',
  path: '/estates/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatesEstateIdRoute = EstatesEstateIdRouteImport.update({
  id: '/estates/$estateId',
  path: '/estates/$estateId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVaultRoute = DashboardVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObituaryRoute = DashboardObituaryRouteImport.update({
  id: '/obituary',
  path: '/obituary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemoirsRoute = DashboardMemoirsRouteImport.update({
  id: '/memoirs',
  path: '/memoirs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEstatesRoute = DashboardEstatesRouteImport.update({
  id: '/estates',
  path: '/estates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBeneficiariesRoute = DashboardBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssetsRoute = DashboardAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => DashboardRoute,
} as any)
const EstatesEstateIdIndexRoute = EstatesEstateIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdVaultRoute = EstatesEstateIdVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdSettingsRoute = EstatesEstateIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdObituaryRoute = EstatesEstateIdObituaryRouteImport.update({
  id: '/obituary',
  path: '/obituary',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdNotificationsRoute =
  EstatesEstateIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any)
const EstatesEstateIdMemoirsRoute = EstatesEstateIdMemoirsRouteImport.update({
  id: '/memoirs',
  path: '/memoirs',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdEstatesRoute = EstatesEstateIdEstatesRouteImport.update({
  id: '/estates',
  path: '/estates',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdDashboardRoute =
  EstatesEstateIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any)
const EstatesEstateIdBeneficiariesRoute =
  EstatesEstateIdBeneficiariesRouteImport.update({
    id: '/beneficiaries',
    path: '/beneficiaries',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any)
const EstatesEstateIdAttestationRoute =
  EstatesEstateIdAttestationRouteImport.update({
    id: '/attestation',
    path: '/attestation',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any)
const EstatesEstateIdAssetsRoute = EstatesEstateIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesRoute
  '/dashboard/estates': typeof DashboardEstatesRoute
  '/dashboard/memoirs': typeof DashboardMemoirsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/obituary': typeof DashboardObituaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/estates/$estateId': typeof EstatesEstateIdRouteWithChildren
  '/estates/create': typeof EstatesCreateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/estates/$estateId/assets': typeof EstatesEstateIdAssetsRoute
  '/estates/$estateId/attestation': typeof EstatesEstateIdAttestationRoute
  '/estates/$estateId/beneficiaries': typeof EstatesEstateIdBeneficiariesRoute
  '/estates/$estateId/dashboard': typeof EstatesEstateIdDashboardRoute
  '/estates/$estateId/estates': typeof EstatesEstateIdEstatesRoute
  '/estates/$estateId/memoirs': typeof EstatesEstateIdMemoirsRoute
  '/estates/$estateId/notifications': typeof EstatesEstateIdNotificationsRoute
  '/estates/$estateId/obituary': typeof EstatesEstateIdObituaryRoute
  '/estates/$estateId/settings': typeof EstatesEstateIdSettingsRoute
  '/estates/$estateId/vault': typeof EstatesEstateIdVaultRoute
  '/estates/$estateId/': typeof EstatesEstateIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesRoute
  '/dashboard/estates': typeof DashboardEstatesRoute
  '/dashboard/memoirs': typeof DashboardMemoirsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/obituary': typeof DashboardObituaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/estates/create': typeof EstatesCreateRoute
  '/dashboard': typeof DashboardIndexRoute
  '/estates/$estateId/assets': typeof EstatesEstateIdAssetsRoute
  '/estates/$estateId/attestation': typeof EstatesEstateIdAttestationRoute
  '/estates/$estateId/beneficiaries': typeof EstatesEstateIdBeneficiariesRoute
  '/estates/$estateId/dashboard': typeof EstatesEstateIdDashboardRoute
  '/estates/$estateId/estates': typeof EstatesEstateIdEstatesRoute
  '/estates/$estateId/memoirs': typeof EstatesEstateIdMemoirsRoute
  '/estates/$estateId/notifications': typeof EstatesEstateIdNotificationsRoute
  '/estates/$estateId/obituary': typeof EstatesEstateIdObituaryRoute
  '/estates/$estateId/settings': typeof EstatesEstateIdSettingsRoute
  '/estates/$estateId/vault': typeof EstatesEstateIdVaultRoute
  '/estates/$estateId': typeof EstatesEstateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesRoute
  '/dashboard/estates': typeof DashboardEstatesRoute
  '/dashboard/memoirs': typeof DashboardMemoirsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/obituary': typeof DashboardObituaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/estates/$estateId': typeof EstatesEstateIdRouteWithChildren
  '/estates/create': typeof EstatesCreateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/estates/$estateId/assets': typeof EstatesEstateIdAssetsRoute
  '/estates/$estateId/attestation': typeof EstatesEstateIdAttestationRoute
  '/estates/$estateId/beneficiaries': typeof EstatesEstateIdBeneficiariesRoute
  '/estates/$estateId/dashboard': typeof EstatesEstateIdDashboardRoute
  '/estates/$estateId/estates': typeof EstatesEstateIdEstatesRoute
  '/estates/$estateId/memoirs': typeof EstatesEstateIdMemoirsRoute
  '/estates/$estateId/notifications': typeof EstatesEstateIdNotificationsRoute
  '/estates/$estateId/obituary': typeof EstatesEstateIdObituaryRoute
  '/estates/$estateId/settings': typeof EstatesEstateIdSettingsRoute
  '/estates/$estateId/vault': typeof EstatesEstateIdVaultRoute
  '/estates/$estateId/': typeof EstatesEstateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/assets'
    | '/dashboard/beneficiaries'
    | '/dashboard/estates'
    | '/dashboard/memoirs'
    | '/dashboard/notifications'
    | '/dashboard/obituary'
    | '/dashboard/settings'
    | '/dashboard/vault'
    | '/estates/$estateId'
    | '/estates/create'
    | '/dashboard/'
    | '/estates/$estateId/assets'
    | '/estates/$estateId/attestation'
    | '/estates/$estateId/beneficiaries'
    | '/estates/$estateId/dashboard'
    | '/estates/$estateId/estates'
    | '/estates/$estateId/memoirs'
    | '/estates/$estateId/notifications'
    | '/estates/$estateId/obituary'
    | '/estates/$estateId/settings'
    | '/estates/$estateId/vault'
    | '/estates/$estateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/assets'
    | '/dashboard/beneficiaries'
    | '/dashboard/estates'
    | '/dashboard/memoirs'
    | '/dashboard/notifications'
    | '/dashboard/obituary'
    | '/dashboard/settings'
    | '/dashboard/vault'
    | '/estates/create'
    | '/dashboard'
    | '/estates/$estateId/assets'
    | '/estates/$estateId/attestation'
    | '/estates/$estateId/beneficiaries'
    | '/estates/$estateId/dashboard'
    | '/estates/$estateId/estates'
    | '/estates/$estateId/memoirs'
    | '/estates/$estateId/notifications'
    | '/estates/$estateId/obituary'
    | '/estates/$estateId/settings'
    | '/estates/$estateId/vault'
    | '/estates/$estateId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/assets'
    | '/dashboard/beneficiaries'
    | '/dashboard/estates'
    | '/dashboard/memoirs'
    | '/dashboard/notifications'
    | '/dashboard/obituary'
    | '/dashboard/settings'
    | '/dashboard/vault'
    | '/estates/$estateId'
    | '/estates/create'
    | '/dashboard/'
    | '/estates/$estateId/assets'
    | '/estates/$estateId/attestation'
    | '/estates/$estateId/beneficiaries'
    | '/estates/$estateId/dashboard'
    | '/estates/$estateId/estates'
    | '/estates/$estateId/memoirs'
    | '/estates/$estateId/notifications'
    | '/estates/$estateId/obituary'
    | '/estates/$estateId/settings'
    | '/estates/$estateId/vault'
    | '/estates/$estateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  EstatesEstateIdRoute: typeof EstatesEstateIdRouteWithChildren
  EstatesCreateRoute: typeof EstatesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/estates/create': {
      id: '/estates/create'
      path: '/estates/create'
      fullPath: '/estates/create'
      preLoaderRoute: typeof EstatesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estates/$estateId': {
      id: '/estates/$estateId'
      path: '/estates/$estateId'
      fullPath: '/estates/$estateId'
      preLoaderRoute: typeof EstatesEstateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vault': {
      id: '/dashboard/vault'
      path: '/vault'
      fullPath: '/dashboard/vault'
      preLoaderRoute: typeof DashboardVaultRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/obituary': {
      id: '/dashboard/obituary'
      path: '/obituary'
      fullPath: '/dashboard/obituary'
      preLoaderRoute: typeof DashboardObituaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/memoirs': {
      id: '/dashboard/memoirs'
      path: '/memoirs'
      fullPath: '/dashboard/memoirs'
      preLoaderRoute: typeof DashboardMemoirsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/estates': {
      id: '/dashboard/estates'
      path: '/estates'
      fullPath: '/dashboard/estates'
      preLoaderRoute: typeof DashboardEstatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/beneficiaries': {
      id: '/dashboard/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/dashboard/beneficiaries'
      preLoaderRoute: typeof DashboardBeneficiariesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assets': {
      id: '/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof DashboardAssetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/estates/$estateId/': {
      id: '/estates/$estateId/'
      path: '/'
      fullPath: '/estates/$estateId/'
      preLoaderRoute: typeof EstatesEstateIdIndexRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/vault': {
      id: '/estates/$estateId/vault'
      path: '/vault'
      fullPath: '/estates/$estateId/vault'
      preLoaderRoute: typeof EstatesEstateIdVaultRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/settings': {
      id: '/estates/$estateId/settings'
      path: '/settings'
      fullPath: '/estates/$estateId/settings'
      preLoaderRoute: typeof EstatesEstateIdSettingsRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/obituary': {
      id: '/estates/$estateId/obituary'
      path: '/obituary'
      fullPath: '/estates/$estateId/obituary'
      preLoaderRoute: typeof EstatesEstateIdObituaryRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/notifications': {
      id: '/estates/$estateId/notifications'
      path: '/notifications'
      fullPath: '/estates/$estateId/notifications'
      preLoaderRoute: typeof EstatesEstateIdNotificationsRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/memoirs': {
      id: '/estates/$estateId/memoirs'
      path: '/memoirs'
      fullPath: '/estates/$estateId/memoirs'
      preLoaderRoute: typeof EstatesEstateIdMemoirsRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/estates': {
      id: '/estates/$estateId/estates'
      path: '/estates'
      fullPath: '/estates/$estateId/estates'
      preLoaderRoute: typeof EstatesEstateIdEstatesRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/dashboard': {
      id: '/estates/$estateId/dashboard'
      path: '/dashboard'
      fullPath: '/estates/$estateId/dashboard'
      preLoaderRoute: typeof EstatesEstateIdDashboardRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/beneficiaries': {
      id: '/estates/$estateId/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/estates/$estateId/beneficiaries'
      preLoaderRoute: typeof EstatesEstateIdBeneficiariesRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/attestation': {
      id: '/estates/$estateId/attestation'
      path: '/attestation'
      fullPath: '/estates/$estateId/attestation'
      preLoaderRoute: typeof EstatesEstateIdAttestationRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/assets': {
      id: '/estates/$estateId/assets'
      path: '/assets'
      fullPath: '/estates/$estateId/assets'
      preLoaderRoute: typeof EstatesEstateIdAssetsRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAssetsRoute: typeof DashboardAssetsRoute
  DashboardBeneficiariesRoute: typeof DashboardBeneficiariesRoute
  DashboardEstatesRoute: typeof DashboardEstatesRoute
  DashboardMemoirsRoute: typeof DashboardMemoirsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardObituaryRoute: typeof DashboardObituaryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVaultRoute: typeof DashboardVaultRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssetsRoute: DashboardAssetsRoute,
  DashboardBeneficiariesRoute: DashboardBeneficiariesRoute,
  DashboardEstatesRoute: DashboardEstatesRoute,
  DashboardMemoirsRoute: DashboardMemoirsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardObituaryRoute: DashboardObituaryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVaultRoute: DashboardVaultRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EstatesEstateIdRouteChildren {
  EstatesEstateIdAssetsRoute: typeof EstatesEstateIdAssetsRoute
  EstatesEstateIdAttestationRoute: typeof EstatesEstateIdAttestationRoute
  EstatesEstateIdBeneficiariesRoute: typeof EstatesEstateIdBeneficiariesRoute
  EstatesEstateIdDashboardRoute: typeof EstatesEstateIdDashboardRoute
  EstatesEstateIdEstatesRoute: typeof EstatesEstateIdEstatesRoute
  EstatesEstateIdMemoirsRoute: typeof EstatesEstateIdMemoirsRoute
  EstatesEstateIdNotificationsRoute: typeof EstatesEstateIdNotificationsRoute
  EstatesEstateIdObituaryRoute: typeof EstatesEstateIdObituaryRoute
  EstatesEstateIdSettingsRoute: typeof EstatesEstateIdSettingsRoute
  EstatesEstateIdVaultRoute: typeof EstatesEstateIdVaultRoute
  EstatesEstateIdIndexRoute: typeof EstatesEstateIdIndexRoute
}

const EstatesEstateIdRouteChildren: EstatesEstateIdRouteChildren = {
  EstatesEstateIdAssetsRoute: EstatesEstateIdAssetsRoute,
  EstatesEstateIdAttestationRoute: EstatesEstateIdAttestationRoute,
  EstatesEstateIdBeneficiariesRoute: EstatesEstateIdBeneficiariesRoute,
  EstatesEstateIdDashboardRoute: EstatesEstateIdDashboardRoute,
  EstatesEstateIdEstatesRoute: EstatesEstateIdEstatesRoute,
  EstatesEstateIdMemoirsRoute: EstatesEstateIdMemoirsRoute,
  EstatesEstateIdNotificationsRoute: EstatesEstateIdNotificationsRoute,
  EstatesEstateIdObituaryRoute: EstatesEstateIdObituaryRoute,
  EstatesEstateIdSettingsRoute: EstatesEstateIdSettingsRoute,
  EstatesEstateIdVaultRoute: EstatesEstateIdVaultRoute,
  EstatesEstateIdIndexRoute: EstatesEstateIdIndexRoute,
}

const EstatesEstateIdRouteWithChildren = EstatesEstateIdRoute._addFileChildren(
  EstatesEstateIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  EstatesEstateIdRoute: EstatesEstateIdRouteWithChildren,
  EstatesCreateRoute: EstatesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
