/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVaultRouteImport } from './routes/dashboard.vault'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardObituaryRouteImport } from './routes/dashboard.obituary'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMemoirsRouteImport } from './routes/dashboard.memoirs'
import { Route as DashboardEstatesRouteImport } from './routes/dashboard.estates'
import { Route as DashboardBeneficiariesRouteImport } from './routes/dashboard.beneficiaries'
import { Route as DashboardAssetsRouteImport } from './routes/dashboard.assets'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVaultRoute = DashboardVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObituaryRoute = DashboardObituaryRouteImport.update({
  id: '/obituary',
  path: '/obituary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemoirsRoute = DashboardMemoirsRouteImport.update({
  id: '/memoirs',
  path: '/memoirs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEstatesRoute = DashboardEstatesRouteImport.update({
  id: '/estates',
  path: '/estates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBeneficiariesRoute = DashboardBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssetsRoute = DashboardAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesRoute
  '/dashboard/estates': typeof DashboardEstatesRoute
  '/dashboard/memoirs': typeof DashboardMemoirsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/obituary': typeof DashboardObituaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesRoute
  '/dashboard/estates': typeof DashboardEstatesRoute
  '/dashboard/memoirs': typeof DashboardMemoirsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/obituary': typeof DashboardObituaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesRoute
  '/dashboard/estates': typeof DashboardEstatesRoute
  '/dashboard/memoirs': typeof DashboardMemoirsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/obituary': typeof DashboardObituaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/assets'
    | '/dashboard/beneficiaries'
    | '/dashboard/estates'
    | '/dashboard/memoirs'
    | '/dashboard/notifications'
    | '/dashboard/obituary'
    | '/dashboard/settings'
    | '/dashboard/vault'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/assets'
    | '/dashboard/beneficiaries'
    | '/dashboard/estates'
    | '/dashboard/memoirs'
    | '/dashboard/notifications'
    | '/dashboard/obituary'
    | '/dashboard/settings'
    | '/dashboard/vault'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/assets'
    | '/dashboard/beneficiaries'
    | '/dashboard/estates'
    | '/dashboard/memoirs'
    | '/dashboard/notifications'
    | '/dashboard/obituary'
    | '/dashboard/settings'
    | '/dashboard/vault'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vault': {
      id: '/dashboard/vault'
      path: '/vault'
      fullPath: '/dashboard/vault'
      preLoaderRoute: typeof DashboardVaultRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/obituary': {
      id: '/dashboard/obituary'
      path: '/obituary'
      fullPath: '/dashboard/obituary'
      preLoaderRoute: typeof DashboardObituaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/memoirs': {
      id: '/dashboard/memoirs'
      path: '/memoirs'
      fullPath: '/dashboard/memoirs'
      preLoaderRoute: typeof DashboardMemoirsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/estates': {
      id: '/dashboard/estates'
      path: '/estates'
      fullPath: '/dashboard/estates'
      preLoaderRoute: typeof DashboardEstatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/beneficiaries': {
      id: '/dashboard/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/dashboard/beneficiaries'
      preLoaderRoute: typeof DashboardBeneficiariesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assets': {
      id: '/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof DashboardAssetsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAssetsRoute: typeof DashboardAssetsRoute
  DashboardBeneficiariesRoute: typeof DashboardBeneficiariesRoute
  DashboardEstatesRoute: typeof DashboardEstatesRoute
  DashboardMemoirsRoute: typeof DashboardMemoirsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardObituaryRoute: typeof DashboardObituaryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVaultRoute: typeof DashboardVaultRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssetsRoute: DashboardAssetsRoute,
  DashboardBeneficiariesRoute: DashboardBeneficiariesRoute,
  DashboardEstatesRoute: DashboardEstatesRoute,
  DashboardMemoirsRoute: DashboardMemoirsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardObituaryRoute: DashboardObituaryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVaultRoute: DashboardVaultRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
