/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstatesCreateRouteImport } from './routes/estates.create'
import { Route as EstatesEstateIdRouteImport } from './routes/estates.$estateId'
import { Route as EstatesEstateIdIndexRouteImport } from './routes/estates.$estateId.index'
import { Route as EstatesEstateIdVaultRouteImport } from './routes/estates.$estateId.vault'
import { Route as EstatesEstateIdTimecapsuleRouteImport } from './routes/estates.$estateId.timecapsule'
import { Route as EstatesEstateIdSoulLogRouteImport } from './routes/estates.$estateId.soul-log'
import { Route as EstatesEstateIdSettingsRouteImport } from './routes/estates.$estateId.settings'
import { Route as EstatesEstateIdPricingRouteImport } from './routes/estates.$estateId.pricing'
import { Route as EstatesEstateIdObituaryRouteImport } from './routes/estates.$estateId.obituary'
import { Route as EstatesEstateIdNotificationsRouteImport } from './routes/estates.$estateId.notifications'
import { Route as EstatesEstateIdMemoirsRouteImport } from './routes/estates.$estateId.memoirs'
import { Route as EstatesEstateIdLockboxRouteImport } from './routes/estates.$estateId.lockbox'
import { Route as EstatesEstateIdLifeChaptersRouteImport } from './routes/estates.$estateId.life-chapters'
import { Route as EstatesEstateIdHeirloomsRouteImport } from './routes/estates.$estateId.heirlooms'
import { Route as EstatesEstateIdEstatesRouteImport } from './routes/estates.$estateId.estates'
import { Route as EstatesEstateIdDirectivesRouteImport } from './routes/estates.$estateId.directives'
import { Route as EstatesEstateIdDashboardRouteImport } from './routes/estates.$estateId.dashboard'
import { Route as EstatesEstateIdBeneficiariesRouteImport } from './routes/estates.$estateId.beneficiaries'
import { Route as EstatesEstateIdAttestationRouteImport } from './routes/estates.$estateId.attestation'
import { Route as EstatesEstateIdAssetsRouteImport } from './routes/estates.$estateId.assets'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatesCreateRoute = EstatesCreateRouteImport.update({
  id: '/estates/create',
  path: '/estates/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatesEstateIdRoute = EstatesEstateIdRouteImport.update({
  id: '/estates/$estateId',
  path: '/estates/$estateId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatesEstateIdIndexRoute = EstatesEstateIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdVaultRoute = EstatesEstateIdVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => EstatesEstateIdRoute,
} as any).lazy(() =>
  import('./routes/estates.$estateId.vault.lazy').then((d) => d.Route),
)
const EstatesEstateIdTimecapsuleRoute =
  EstatesEstateIdTimecapsuleRouteImport.update({
    id: '/timecapsule',
    path: '/timecapsule',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any).lazy(() =>
    import('./routes/estates.$estateId.timecapsule.lazy').then((d) => d.Route),
  )
const EstatesEstateIdSoulLogRoute = EstatesEstateIdSoulLogRouteImport.update({
  id: '/soul-log',
  path: '/soul-log',
  getParentRoute: () => EstatesEstateIdRoute,
} as any).lazy(() =>
  import('./routes/estates.$estateId.soul-log.lazy').then((d) => d.Route),
)
const EstatesEstateIdSettingsRoute = EstatesEstateIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdPricingRoute = EstatesEstateIdPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdObituaryRoute = EstatesEstateIdObituaryRouteImport.update({
  id: '/obituary',
  path: '/obituary',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdNotificationsRoute =
  EstatesEstateIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any)
const EstatesEstateIdMemoirsRoute = EstatesEstateIdMemoirsRouteImport.update({
  id: '/memoirs',
  path: '/memoirs',
  getParentRoute: () => EstatesEstateIdRoute,
} as any).lazy(() =>
  import('./routes/estates.$estateId.memoirs.lazy').then((d) => d.Route),
)
const EstatesEstateIdLockboxRoute = EstatesEstateIdLockboxRouteImport.update({
  id: '/lockbox',
  path: '/lockbox',
  getParentRoute: () => EstatesEstateIdRoute,
} as any).lazy(() =>
  import('./routes/estates.$estateId.lockbox.lazy').then((d) => d.Route),
)
const EstatesEstateIdLifeChaptersRoute =
  EstatesEstateIdLifeChaptersRouteImport.update({
    id: '/life-chapters',
    path: '/life-chapters',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any)
const EstatesEstateIdHeirloomsRoute =
  EstatesEstateIdHeirloomsRouteImport.update({
    id: '/heirlooms',
    path: '/heirlooms',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any)
const EstatesEstateIdEstatesRoute = EstatesEstateIdEstatesRouteImport.update({
  id: '/estates',
  path: '/estates',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)
const EstatesEstateIdDirectivesRoute =
  EstatesEstateIdDirectivesRouteImport.update({
    id: '/directives',
    path: '/directives',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any)
const EstatesEstateIdDashboardRoute =
  EstatesEstateIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any).lazy(() =>
    import('./routes/estates.$estateId.dashboard.lazy').then((d) => d.Route),
  )
const EstatesEstateIdBeneficiariesRoute =
  EstatesEstateIdBeneficiariesRouteImport.update({
    id: '/beneficiaries',
    path: '/beneficiaries',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any)
const EstatesEstateIdAttestationRoute =
  EstatesEstateIdAttestationRouteImport.update({
    id: '/attestation',
    path: '/attestation',
    getParentRoute: () => EstatesEstateIdRoute,
  } as any)
const EstatesEstateIdAssetsRoute = EstatesEstateIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => EstatesEstateIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/estates/$estateId': typeof EstatesEstateIdRouteWithChildren
  '/estates/create': typeof EstatesCreateRoute
  '/estates/$estateId/assets': typeof EstatesEstateIdAssetsRoute
  '/estates/$estateId/attestation': typeof EstatesEstateIdAttestationRoute
  '/estates/$estateId/beneficiaries': typeof EstatesEstateIdBeneficiariesRoute
  '/estates/$estateId/dashboard': typeof EstatesEstateIdDashboardRoute
  '/estates/$estateId/directives': typeof EstatesEstateIdDirectivesRoute
  '/estates/$estateId/estates': typeof EstatesEstateIdEstatesRoute
  '/estates/$estateId/heirlooms': typeof EstatesEstateIdHeirloomsRoute
  '/estates/$estateId/life-chapters': typeof EstatesEstateIdLifeChaptersRoute
  '/estates/$estateId/lockbox': typeof EstatesEstateIdLockboxRoute
  '/estates/$estateId/memoirs': typeof EstatesEstateIdMemoirsRoute
  '/estates/$estateId/notifications': typeof EstatesEstateIdNotificationsRoute
  '/estates/$estateId/obituary': typeof EstatesEstateIdObituaryRoute
  '/estates/$estateId/pricing': typeof EstatesEstateIdPricingRoute
  '/estates/$estateId/settings': typeof EstatesEstateIdSettingsRoute
  '/estates/$estateId/soul-log': typeof EstatesEstateIdSoulLogRoute
  '/estates/$estateId/timecapsule': typeof EstatesEstateIdTimecapsuleRoute
  '/estates/$estateId/vault': typeof EstatesEstateIdVaultRoute
  '/estates/$estateId/': typeof EstatesEstateIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/estates/create': typeof EstatesCreateRoute
  '/estates/$estateId/assets': typeof EstatesEstateIdAssetsRoute
  '/estates/$estateId/attestation': typeof EstatesEstateIdAttestationRoute
  '/estates/$estateId/beneficiaries': typeof EstatesEstateIdBeneficiariesRoute
  '/estates/$estateId/dashboard': typeof EstatesEstateIdDashboardRoute
  '/estates/$estateId/directives': typeof EstatesEstateIdDirectivesRoute
  '/estates/$estateId/estates': typeof EstatesEstateIdEstatesRoute
  '/estates/$estateId/heirlooms': typeof EstatesEstateIdHeirloomsRoute
  '/estates/$estateId/life-chapters': typeof EstatesEstateIdLifeChaptersRoute
  '/estates/$estateId/lockbox': typeof EstatesEstateIdLockboxRoute
  '/estates/$estateId/memoirs': typeof EstatesEstateIdMemoirsRoute
  '/estates/$estateId/notifications': typeof EstatesEstateIdNotificationsRoute
  '/estates/$estateId/obituary': typeof EstatesEstateIdObituaryRoute
  '/estates/$estateId/pricing': typeof EstatesEstateIdPricingRoute
  '/estates/$estateId/settings': typeof EstatesEstateIdSettingsRoute
  '/estates/$estateId/soul-log': typeof EstatesEstateIdSoulLogRoute
  '/estates/$estateId/timecapsule': typeof EstatesEstateIdTimecapsuleRoute
  '/estates/$estateId/vault': typeof EstatesEstateIdVaultRoute
  '/estates/$estateId': typeof EstatesEstateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/estates/$estateId': typeof EstatesEstateIdRouteWithChildren
  '/estates/create': typeof EstatesCreateRoute
  '/estates/$estateId/assets': typeof EstatesEstateIdAssetsRoute
  '/estates/$estateId/attestation': typeof EstatesEstateIdAttestationRoute
  '/estates/$estateId/beneficiaries': typeof EstatesEstateIdBeneficiariesRoute
  '/estates/$estateId/dashboard': typeof EstatesEstateIdDashboardRoute
  '/estates/$estateId/directives': typeof EstatesEstateIdDirectivesRoute
  '/estates/$estateId/estates': typeof EstatesEstateIdEstatesRoute
  '/estates/$estateId/heirlooms': typeof EstatesEstateIdHeirloomsRoute
  '/estates/$estateId/life-chapters': typeof EstatesEstateIdLifeChaptersRoute
  '/estates/$estateId/lockbox': typeof EstatesEstateIdLockboxRoute
  '/estates/$estateId/memoirs': typeof EstatesEstateIdMemoirsRoute
  '/estates/$estateId/notifications': typeof EstatesEstateIdNotificationsRoute
  '/estates/$estateId/obituary': typeof EstatesEstateIdObituaryRoute
  '/estates/$estateId/pricing': typeof EstatesEstateIdPricingRoute
  '/estates/$estateId/settings': typeof EstatesEstateIdSettingsRoute
  '/estates/$estateId/soul-log': typeof EstatesEstateIdSoulLogRoute
  '/estates/$estateId/timecapsule': typeof EstatesEstateIdTimecapsuleRoute
  '/estates/$estateId/vault': typeof EstatesEstateIdVaultRoute
  '/estates/$estateId/': typeof EstatesEstateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/estates/$estateId'
    | '/estates/create'
    | '/estates/$estateId/assets'
    | '/estates/$estateId/attestation'
    | '/estates/$estateId/beneficiaries'
    | '/estates/$estateId/dashboard'
    | '/estates/$estateId/directives'
    | '/estates/$estateId/estates'
    | '/estates/$estateId/heirlooms'
    | '/estates/$estateId/life-chapters'
    | '/estates/$estateId/lockbox'
    | '/estates/$estateId/memoirs'
    | '/estates/$estateId/notifications'
    | '/estates/$estateId/obituary'
    | '/estates/$estateId/pricing'
    | '/estates/$estateId/settings'
    | '/estates/$estateId/soul-log'
    | '/estates/$estateId/timecapsule'
    | '/estates/$estateId/vault'
    | '/estates/$estateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/estates/create'
    | '/estates/$estateId/assets'
    | '/estates/$estateId/attestation'
    | '/estates/$estateId/beneficiaries'
    | '/estates/$estateId/dashboard'
    | '/estates/$estateId/directives'
    | '/estates/$estateId/estates'
    | '/estates/$estateId/heirlooms'
    | '/estates/$estateId/life-chapters'
    | '/estates/$estateId/lockbox'
    | '/estates/$estateId/memoirs'
    | '/estates/$estateId/notifications'
    | '/estates/$estateId/obituary'
    | '/estates/$estateId/pricing'
    | '/estates/$estateId/settings'
    | '/estates/$estateId/soul-log'
    | '/estates/$estateId/timecapsule'
    | '/estates/$estateId/vault'
    | '/estates/$estateId'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/estates/$estateId'
    | '/estates/create'
    | '/estates/$estateId/assets'
    | '/estates/$estateId/attestation'
    | '/estates/$estateId/beneficiaries'
    | '/estates/$estateId/dashboard'
    | '/estates/$estateId/directives'
    | '/estates/$estateId/estates'
    | '/estates/$estateId/heirlooms'
    | '/estates/$estateId/life-chapters'
    | '/estates/$estateId/lockbox'
    | '/estates/$estateId/memoirs'
    | '/estates/$estateId/notifications'
    | '/estates/$estateId/obituary'
    | '/estates/$estateId/pricing'
    | '/estates/$estateId/settings'
    | '/estates/$estateId/soul-log'
    | '/estates/$estateId/timecapsule'
    | '/estates/$estateId/vault'
    | '/estates/$estateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  EstatesEstateIdRoute: typeof EstatesEstateIdRouteWithChildren
  EstatesCreateRoute: typeof EstatesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estates/create': {
      id: '/estates/create'
      path: '/estates/create'
      fullPath: '/estates/create'
      preLoaderRoute: typeof EstatesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estates/$estateId': {
      id: '/estates/$estateId'
      path: '/estates/$estateId'
      fullPath: '/estates/$estateId'
      preLoaderRoute: typeof EstatesEstateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estates/$estateId/': {
      id: '/estates/$estateId/'
      path: '/'
      fullPath: '/estates/$estateId/'
      preLoaderRoute: typeof EstatesEstateIdIndexRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/vault': {
      id: '/estates/$estateId/vault'
      path: '/vault'
      fullPath: '/estates/$estateId/vault'
      preLoaderRoute: typeof EstatesEstateIdVaultRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/timecapsule': {
      id: '/estates/$estateId/timecapsule'
      path: '/timecapsule'
      fullPath: '/estates/$estateId/timecapsule'
      preLoaderRoute: typeof EstatesEstateIdTimecapsuleRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/soul-log': {
      id: '/estates/$estateId/soul-log'
      path: '/soul-log'
      fullPath: '/estates/$estateId/soul-log'
      preLoaderRoute: typeof EstatesEstateIdSoulLogRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/settings': {
      id: '/estates/$estateId/settings'
      path: '/settings'
      fullPath: '/estates/$estateId/settings'
      preLoaderRoute: typeof EstatesEstateIdSettingsRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/pricing': {
      id: '/estates/$estateId/pricing'
      path: '/pricing'
      fullPath: '/estates/$estateId/pricing'
      preLoaderRoute: typeof EstatesEstateIdPricingRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/obituary': {
      id: '/estates/$estateId/obituary'
      path: '/obituary'
      fullPath: '/estates/$estateId/obituary'
      preLoaderRoute: typeof EstatesEstateIdObituaryRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/notifications': {
      id: '/estates/$estateId/notifications'
      path: '/notifications'
      fullPath: '/estates/$estateId/notifications'
      preLoaderRoute: typeof EstatesEstateIdNotificationsRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/memoirs': {
      id: '/estates/$estateId/memoirs'
      path: '/memoirs'
      fullPath: '/estates/$estateId/memoirs'
      preLoaderRoute: typeof EstatesEstateIdMemoirsRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/lockbox': {
      id: '/estates/$estateId/lockbox'
      path: '/lockbox'
      fullPath: '/estates/$estateId/lockbox'
      preLoaderRoute: typeof EstatesEstateIdLockboxRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/life-chapters': {
      id: '/estates/$estateId/life-chapters'
      path: '/life-chapters'
      fullPath: '/estates/$estateId/life-chapters'
      preLoaderRoute: typeof EstatesEstateIdLifeChaptersRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/heirlooms': {
      id: '/estates/$estateId/heirlooms'
      path: '/heirlooms'
      fullPath: '/estates/$estateId/heirlooms'
      preLoaderRoute: typeof EstatesEstateIdHeirloomsRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/estates': {
      id: '/estates/$estateId/estates'
      path: '/estates'
      fullPath: '/estates/$estateId/estates'
      preLoaderRoute: typeof EstatesEstateIdEstatesRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/directives': {
      id: '/estates/$estateId/directives'
      path: '/directives'
      fullPath: '/estates/$estateId/directives'
      preLoaderRoute: typeof EstatesEstateIdDirectivesRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/dashboard': {
      id: '/estates/$estateId/dashboard'
      path: '/dashboard'
      fullPath: '/estates/$estateId/dashboard'
      preLoaderRoute: typeof EstatesEstateIdDashboardRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/beneficiaries': {
      id: '/estates/$estateId/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/estates/$estateId/beneficiaries'
      preLoaderRoute: typeof EstatesEstateIdBeneficiariesRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/attestation': {
      id: '/estates/$estateId/attestation'
      path: '/attestation'
      fullPath: '/estates/$estateId/attestation'
      preLoaderRoute: typeof EstatesEstateIdAttestationRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
    '/estates/$estateId/assets': {
      id: '/estates/$estateId/assets'
      path: '/assets'
      fullPath: '/estates/$estateId/assets'
      preLoaderRoute: typeof EstatesEstateIdAssetsRouteImport
      parentRoute: typeof EstatesEstateIdRoute
    }
  }
}

interface EstatesEstateIdRouteChildren {
  EstatesEstateIdAssetsRoute: typeof EstatesEstateIdAssetsRoute
  EstatesEstateIdAttestationRoute: typeof EstatesEstateIdAttestationRoute
  EstatesEstateIdBeneficiariesRoute: typeof EstatesEstateIdBeneficiariesRoute
  EstatesEstateIdDashboardRoute: typeof EstatesEstateIdDashboardRoute
  EstatesEstateIdDirectivesRoute: typeof EstatesEstateIdDirectivesRoute
  EstatesEstateIdEstatesRoute: typeof EstatesEstateIdEstatesRoute
  EstatesEstateIdHeirloomsRoute: typeof EstatesEstateIdHeirloomsRoute
  EstatesEstateIdLifeChaptersRoute: typeof EstatesEstateIdLifeChaptersRoute
  EstatesEstateIdLockboxRoute: typeof EstatesEstateIdLockboxRoute
  EstatesEstateIdMemoirsRoute: typeof EstatesEstateIdMemoirsRoute
  EstatesEstateIdNotificationsRoute: typeof EstatesEstateIdNotificationsRoute
  EstatesEstateIdObituaryRoute: typeof EstatesEstateIdObituaryRoute
  EstatesEstateIdPricingRoute: typeof EstatesEstateIdPricingRoute
  EstatesEstateIdSettingsRoute: typeof EstatesEstateIdSettingsRoute
  EstatesEstateIdSoulLogRoute: typeof EstatesEstateIdSoulLogRoute
  EstatesEstateIdTimecapsuleRoute: typeof EstatesEstateIdTimecapsuleRoute
  EstatesEstateIdVaultRoute: typeof EstatesEstateIdVaultRoute
  EstatesEstateIdIndexRoute: typeof EstatesEstateIdIndexRoute
}

const EstatesEstateIdRouteChildren: EstatesEstateIdRouteChildren = {
  EstatesEstateIdAssetsRoute: EstatesEstateIdAssetsRoute,
  EstatesEstateIdAttestationRoute: EstatesEstateIdAttestationRoute,
  EstatesEstateIdBeneficiariesRoute: EstatesEstateIdBeneficiariesRoute,
  EstatesEstateIdDashboardRoute: EstatesEstateIdDashboardRoute,
  EstatesEstateIdDirectivesRoute: EstatesEstateIdDirectivesRoute,
  EstatesEstateIdEstatesRoute: EstatesEstateIdEstatesRoute,
  EstatesEstateIdHeirloomsRoute: EstatesEstateIdHeirloomsRoute,
  EstatesEstateIdLifeChaptersRoute: EstatesEstateIdLifeChaptersRoute,
  EstatesEstateIdLockboxRoute: EstatesEstateIdLockboxRoute,
  EstatesEstateIdMemoirsRoute: EstatesEstateIdMemoirsRoute,
  EstatesEstateIdNotificationsRoute: EstatesEstateIdNotificationsRoute,
  EstatesEstateIdObituaryRoute: EstatesEstateIdObituaryRoute,
  EstatesEstateIdPricingRoute: EstatesEstateIdPricingRoute,
  EstatesEstateIdSettingsRoute: EstatesEstateIdSettingsRoute,
  EstatesEstateIdSoulLogRoute: EstatesEstateIdSoulLogRoute,
  EstatesEstateIdTimecapsuleRoute: EstatesEstateIdTimecapsuleRoute,
  EstatesEstateIdVaultRoute: EstatesEstateIdVaultRoute,
  EstatesEstateIdIndexRoute: EstatesEstateIdIndexRoute,
}

const EstatesEstateIdRouteWithChildren = EstatesEstateIdRoute._addFileChildren(
  EstatesEstateIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  EstatesEstateIdRoute: EstatesEstateIdRouteWithChildren,
  EstatesCreateRoute: EstatesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
